### ISSUE TITLE
cacert issue

### ISSUE THREAD

**Issue by S0N-0F-A-S0N** [iAmGhost/VitaUpdateBlocker#5]
Here's the issue:

==================================
VitaUpdateBlocker v1.2
http://iamghost.kr
==================================
[Wed Jun  3 19:30:09 2015] Listening on 192.168.64.104:8080
[Wed Jun  3 19:30:09 2015] Blocking non-related traffic is DISABLED.
Traceback (most recent call last):
  File "/Users/S0N/Desktop/VitaUpdateBlocker-master/vita_update_blocker.py", line 132, in <module>
    main()
  File "/Users/S0N/Desktop/VitaUpdateBlocker-master/vita_update_blocker.py", line 125, in main
    cacert=os.path.expanduser("~/.mitmproxy/mitmproxy-ca.pem")
TypeError: __init__() got an unexpected keyword argument 'cacert'

-----

I would have used pastebin, but it's a small amount of text. Apparently main() cannot execute because there's an issue with cacert. I'm not sure what that line does OR how to fix it, can't find where it's used in the code. Any idea on how to fix it? Also, YES I have installed everything correctly.

**Comment by iAmGhost** [comment]
That's because of update of mitmproxy broken my old source code(and I didn't mentioned which version of mitmproxy should be installed).

I've fixed my code and specified version of mitmproxy in 5e821ce2082a67a543bfedc9eeeffe8066999eee, make sure you have same version of mitmproxy(0.12.1) is installed.
